# Site settings
title: "MAS 341: Graph Theory"
email: "paul.johnson@sheffield.ac.uk"
description: 
baseurl: "/MAS341-Graph-Theory-2017" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
collections:
   lecturenotes:
     output: true
   practiceproblems:
      output: true
github_username:  ptwiddle

# Build settings
markdown: kramdown
